// Generated by CoffeeScript 1.3.3
(function() {

  (function($, window) {
    var Plugin, defaults, document, pluginName;
    pluginName = 'AHider';
    document = window.document;
    defaults = {
      showText: '[ show ]',
      hideText: '[ hide ]',
      toggleButtonClass: 'a-hider-button',
      toggleBoxClass: 'a-hider-box',
      defaultState: 'hidden',
      hiddenClass: 'a-hider-hidden',
      visibleClass: 'a-hider-visible',
      easing: 'swing',
      visibleWords: 15,
      animationTime: 2000,
      onCompleteHide: function() {},
      onCompleteShow: function() {}
    };
    Plugin = (function() {

      function Plugin(element, options) {
        this.element = element;
        if (options == null) {
          options = {};
        }
        this.options = $.extend({}, defaults, options);
        this._defaults = defaults;
        this._name = pluginName;
        this._visibleText = '';
        this._hiddenText = '';
        this._originalText = '';
        this.init();
      }

      Plugin.prototype._prepareText = function(text) {
        var options, self;
        options = this.options;
        self = this;
        this._visibleText = text.trim().split(' ').slice(0, options.visibleWords).join(' ');
        this._hiddenText = text.trim().split(' ').slice(options.visibleWords).join(' ');
        return this._originalText = text;
      };

      Plugin.prototype.init = function() {
        return $(this).each(function() {
          var container, hiddenText, options, self, textHeight, toggleBox, toggleButton, visibleText;
          options = this.options;
          self = this;
          container = this.element;
          toggleButton = container.find('.' + options.toggleButtonClass);
          toggleButton.css('cursor', 'pointer');
          toggleBox = container.find('.' + options.toggleBoxClass);
          this._prepareText(toggleBox.text());
          visibleText = $('<span/>').text(this._visibleText);
          hiddenText = $('<span/>').text(this._hiddenText);
          textHeight = toggleBox.height();
          toggleBox.text('').append(visibleText).append(' ').append(hiddenText).css('overflow', 'hidden');
          if (options.defaultState === 'hidden') {
            toggleButton.addClass(options.hiddenClass).text(options.showText);
            hiddenText.hide();
          } else {
            toggleButton.addClass(options.visibleClass).text(options.hideText);
            hiddenText.show();
          }
          return toggleButton.on('click', function() {
            toggleBox = $(this).siblings('.' + options.toggleBoxClass);
            $(this).toggleClass(options.hiddenClass).toggleClass(options.visibleClass);
            if ($(this).is('.' + options.hiddenClass)) {
              $(this).text(options.showText);
              return toggleBox.animate({
                height: visibleText.height()
              }, {
                duration: options.animationTime,
                complete: function() {
                  hiddenText.hide();
                  return options.onCompleteHide();
                },
                easing: options.easing
              });
            } else {
              $(this).text(options.hideText);
              hiddenText.show();
              return toggleBox.css('height', visibleText.height()).animate({
                height: textHeight
              }, {
                duration: options.animationTime,
                complete: function() {
                  return options.onCompleteShow();
                },
                easing: options.easing
              });
            }
          });
        });
      };

      return Plugin;

    })();
    return $.fn[pluginName] = function(options) {
      if (options == null) {
        options = {};
      }
      return this.each(function() {
        if (!$.data(this, "plugin_" + pluginName)) {
          return $.data($(this), "plugin_" + pluginName, new Plugin($(this), options));
        }
      });
    };
  })(jQuery, window);

}).call(this);
